Invoice payment
NilsG-S/team-null-back-end pull request #28
Opened 2017-04-27 20:57 UTC by dlowrey

- Added default values ($50 for copay, random($100, $1300) for invoice
- Updated and modified `src/payment` endpoints to reflect needs and Wiki

2017-04-27 21:05 UTC, NilsG-S requested changes
Mostly looks good

2017-04-27 21:05 UTC, NilsG-S commented on src/payments/db.js
> +* getPaymentById: get copay payment information by id
This is supposed to be an invoice payment

2017-04-28 00:04 UTC, dlowrey commented
@NilsG-S done

2017-04-28 01:02 UTC, NilsG-S approved these changes

2017-04-28 17:25 UTC, merged